#!/bin/bash

# invoke with...
# bash <(wget -qO- https://raw.githubusercontent.com/mralexgray/hostess/master/INSTALL)

set -x 

REPO=hostess

# Make sure we're installed, otherwise do it.

HERE_IS="$(basename $(realpath ${0:h}))"
IS_REPO="$(git remote -v)" 

[[ $HERE_IS != $REPO || ! $IS_REPO =~ $REPO ]] && {
	
	echo "danger, not the right git repo!"
	exit

} || {

	git submodule update --init --recursive
	
}

exit
∏
# Set up DNS
. ${0}/../setup/dns.zsh

# Connect
[[ $(hostname) == $HOSTNAME ]] && exit 

/usr/local/bin/ssh root@$HOSTNAME 'bash <(wget -qO- https://raw.githubusercontent.com/mralexgray/GoGoVPS/master/setup/install.zsh)'

